### PR TITLE
[Chater14] Upload 14.1 to 14.2 code

### PR DESCRIPTION
**Pull request by sungwon2054**
# You can change this whatever you want

## What does this PR do?

* 14.1 ~ 14.2 업로드 합니다

## What was the difficult part of this PR?

* ㅠㅠ.. 다못했습니다..ㅠㅠ..

### CODE REVIEW

**Comment by LeeJehwan** [comment]
ch10부분 수정해주세요.

**Comment by sungwon2054** [comment]
수정했습니다.

**Review by LeeJehwan — APPROVED** [review]
고생하셨습니다~ :+1:

**Review by soleileun — APPROVED** [review]
고생하셨습니다 ~ 👍

**Pull request merged**
